FROM node:lts-buster

ENV TZ=Europe/Oslo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y curl git wget locales jq gettext-base

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

WORKDIR /code

EXPOSE 5555

COPY package.json /code

RUN npm config set loglevel warn

RUN npm install --silent

COPY * /code

CMD ["npm", "run", "start"]